name: Build and scan container image

on:
  pull_request:

jobs:
  lint:
    name: Lint Dockerfile with hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint Dockerfile
        # https://github.com/hadolint/hadolint-action
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
          verbose: true

  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        # https://github.com/docker/setup-buildx-action
        uses: docker/setup-buildx-action@v2

      - name: Build only
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          tags: cwlui:scan

      - name: Dockle
        # https://github.com/goodwithtech/dockle-action
        uses: goodwithtech/dockle-action@main
        with:
          image: cwlui:scan
          format: list
          exit-code: '1'
          exit-level: fatal
          ignore: 'CIS-DI-0010'

      - name: Trivy
        # https://github.com/aquasecurity/trivy-action
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: cwlui:scan
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
